### ISSUE TITLE
General plan 

### ISSUE THREAD

**Issue by mkozhukharenko** [mkozhukharenko/ums-frontend#11]
# Plan overview
### Sorted by priority (highest first)
- [x]  #1  [Auth](https://github.com/mkozhukharenko/ums-frontend/issues/1)
- [x] Statistics
- [x] [Intermediate view before rating.](https://github.com/mkozhukharenko/ums-frontend/issues/9)
- [x] [Rating](https://github.com/mkozhukharenko/ums-frontend/issues/10). 
- [ ] View enrolment (list). Relates to[ this task](https://github.com/mkozhukharenko/ums-frontend/issues/5)
- [ ] view person (list). Relates to[ this task](https://github.com/mkozhukharenko/ums-frontend/issues/5)
- [ ] [View one enrolment](https://github.com/mkozhukharenko/ums-frontend/issues/3) (main tab)
- [ ] View one person (main tab)
- [x] Specoffer list. Relates to[ this task](https://github.com/mkozhukharenko/ums-frontend/issues/5)
- [ ] View one enrolment (all tabs)'
- [ ] View one person (all tab)
- [ ] View one specoffer (main tab)
- [ ] Dictionaries view (list)
